name: Build and publish
on:
  schedule:
    - cron: '23 2 * * *'
  push:
  pull_request:



env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: harbor.obeone.cloud
  # github.repository as <account>/<repo>
  IMAGE_NAME: public/docker-nfs-server

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # # Install the cosign tool except on PR
      # # https://github.com/sigstore/cosign-installer
      # - name: Install cosign
      #   if: github.event_name != 'pull_request'
      #   uses: sigstore/cosign-installer@7e0881f8fe90b25e305bbf0309761e9314607e25
      #   with:
      #     cosign-release: 'v1.9.0'


      # Workaround: https://github.com/docker/build-push-action/issues/461
      # - name: Setup Docker buildx
      #   uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PW }}

      - name: Build image
        id: build
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm64
            linux/i386
            linux/armhf
            linux/armel
          pull: true
          load: true
          tags: docker-nfs-server:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-to: type=gha,mode=max
          cache-from: type=gha,mode=max
          
      - name: Finding latest release
        id: version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}


      - name: Parse semver string
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        id: semver_parser 
        uses: booxmedialtd/ws-action-parse-semver@v1
        with: 
          input_string: "${{ steps.version.outputs.release }}"


      - name: Publish image
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        id: push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          push: true
          pull: true
          cache-to: type=gha,mode=max
          cache-from: type=gha,mode=max
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.semver_parser.outputs.major }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.${{ steps.semver_parser.outputs.patch }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v${{ steps.semver_parser.outputs.major }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.${{ steps.semver_parser.outputs.patch }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
